on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Lint
      run: |
        yarn lint

  test:
    name: "Test - Node: ${{ matrix.node_version }} - OS: ${{ matrix.os }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu-latest"
        node_version:
          - "16"
          - "17"
          - "18"

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test with coverage
        run: yarn coverage

      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
